### ISSUE TITLE
[BUG] "Focus on tab ..." commands don't work

### ISSUE THREAD

**Issue by 0qln** [Maldonacho/obsidian-encore-theme#45]
**Describe the Bug**
Some of the `Focus on tab ...` commands don't work when the theme is active.

**To Reproduce**
1. Create a clean vault
2. Install and use Encore theme
3. Bind a hotkey to `Focus on tab group to the right` command
4. Put two tabs next to another
5. Try using the hotkey

**In which mode does the bug occur?**
- [x] Reading/Preview Mode
- [x] Source Mode
- [x] Live Preview

**Which editor are you using?**
(I don't know the difference... the default on I guess?)

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by 0qln** [comment]
Temporary solution: From `themes\Encore\theme.css` Delete lines 467-475:

```css
.workspace-split.mod-vertical.mod-root .workspace-leaf-resize-handle {
  right: -6px;
}

.workspace-split.mod-vertical > .workspace-leaf-resize-handle,
.mod-root .workspace-split.mod-horizontal :not(.mod-vertical) .workspace-leaf-resize-handle {
  bottom: -6px;
}
```
